on:
 push:
  branches:
  - main
permissions:
  pull-requests: write
  contents: write
  repository-projects: write
jobs:
  display-files:
    name: job name display file content
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: display file content
        run: |
          echo "hello world"
          cat test.txt
        shell: bash




          
